name: Tests and Code Coverage

on: [pull_request]

jobs:
  install:
    name: Setup Fastlane
    runs-on: manzanita-standard-v7
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install Fastlane
        run: |
          gem install fastlane
  test_iOS:
    needs: install
    name: iOS Tests
    runs-on: manzanita-standard-v7
    timeout-minutes: 60
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      working-directory: ./builder
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=17.5,name=iPhone 15 Pro"]
        scheme:
            - TealiumCoreTests-iOS
    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v2
      - name: Test - "${{ matrix.scheme }}"
        run: fastlane scan --scheme "${{ matrix.scheme }}" --output_files "${{ matrix.scheme }}" --derived-data-path "./build" --skip_build true --result_bundle true --output_types junit --xcodebuild_formatter "xcbeautify -q --is-ci"  --destination "${{ matrix.destination }}"
        working-directory: ${{env.working-directory}}
  test_macOS:
    needs: install
    name: macOS Tests
    runs-on: manzanita-standard-v7
    timeout-minutes: 60
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      working-directory: ./builder
    strategy:
      matrix:
        destination: ["platform=macOS"]
        scheme:
          - TealiumCoreTests-macOS
    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v2
      - name: Test - "${{ matrix.scheme }}"
        run: rm -rf output && fastlane scan --scheme "${{ matrix.scheme }}" --derived_data_path ./output --code_coverage true --skip_build true --destination "${{ matrix.destination }}"
        working-directory: ${{env.working-directory}}
  test_tvOS:
    needs: install
    name: tvOS Tests
    runs-on: manzanita-standard-v7
    timeout-minutes: 60
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      working-directory: ./builder
    strategy:
      matrix:
        destination: ["platform=tvOS Simulator,name=Apple TV"]
        scheme:
          - TealiumCoreTests-tvOS
    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v2
      - name: Test - "${{ matrix.scheme }}"
        run: rm -rf output && fastlane scan --scheme "${{ matrix.scheme }}" --derived_data_path ./output --code_coverage true --skip_build true  --destination "${{ matrix.destination }}"
        working-directory: ${{env.working-directory}}
